### ISSUE TITLE
proccess blocks openresty

### ISSUE THREAD

**Issue by lordnynex** [bungle/lua-resty-libcjson#4]
I'm experiencing a weird issue using this library in conjunction with resty websockets. It appears to permanently block the entire webserver. Any ideas why this is happening? This only happens while encoding (specifically a table at index 3 of another table).

**Comment by lordnynex** [comment]
Small update. I'm guessing this issue is related to me attempting to serialize > 32bit integers. 

I'm noticing now that I've used cjson that ships with resty, I'm experiencing protocol violations for my particular websocket usage because the resulting encoded integer contains a significand.

**Comment by bungle** [comment]
So, are you using lua-cjson or this, because they are totally different things. I think lua-cjson started as a fork from cjson, but they seem to be totally different these days. I'm not sure about the origins though. I implemented this to original libcjson, but well... it has some niceties, but it is particularly slow on encoding. Decoding is fine though. The encval is recursive, maybe someone could optimize that, not sure. But yes, if you encode a big file with lua-resty-libcjson it will be really slow, and yes, it will block. we could add some yields to it, but it will not make it any faster.

**Comment by bungle** [comment]
Well not sure what is going on, I retried now my lua-resty-libcjson and it is freaking fast even in encoding. I need to do rechecking.

**Comment by lordnynex** [comment]
So you don't see any blocking behavior with the following code?

```lua
json.encode{ "large_int": 9007199254740992 }
```

In a single worker configuration this permanently blocks the webserver requiring restart. There is no debug output, I'd have to do some systemtap profiling to see what exactly it's doing. 

I am able to decode these values, but re-encoding the resulting table causes the hang. 

I do not experience this hang with cjson that ships with openresty.

**Comment by bungle** [comment]
Thanks, I will check it out.

**Comment by bungle** [comment]
Just some benchmarks:
https://github.com/bungle/lua-resty-libcjson/blob/master/README.md#benchmarks

lua-resty-libcjson is slower, but not too much behind.

**Comment by bungle** [comment]
I tried this with both luajit and resty-cli:

```lua
json.encode{ "large_int": 9007199254740992 }
```

It outputted:

```json
{
	"large_int":	9007199254740992
}
```

**Comment by bungle** [comment]
But of course everything in this is blocking (there are no yielding, and no cosockets there that could yield, and everything in OpenResty Lua code is blocking if it doesn't yield at some point). If you are encoding huge files, then `lua-resty-libcjson` will be dead slow. It is recommended to use Lua cJSON for encoding. And when you do that, we keep using `lua-resty-libcjson` at all? I started this because someone asked, that Lua cJSON is not up-to-date and it is not JIT compilable as it uses Lua C API. I thought that Lua cJSON is just a small wrapper around cJSON (libcjson), but it turns out it is totally different thing, And what I found is that Lua cJSON is actually a lot faster than this naive FFI binding that `lua-resty-libcjson` is.

**Comment by lordnynex** [comment]
Well it must be something wrong with my build. Here is the json string/table causing the issue (in my app it is first decoded and then re-encoded)

```javascript
[36,9007199254740992,8299743424320,{},[{"message":"Hello, world!"}]]
```

As you can see, it's not a lot of data. There should be no need to yield etc (even if you could).

I'm quite surprised you get that output. I would expect your testing to show something like 90+E15 which the behavior I'm seeing with cjson that ships with openresty. 

Unfortunately, I've had to modify a ton of client code to ensure that integer generation is capped at some reasonable point. The reason I wanted to use this library is because in the above example, the message table can be nil. As you know, lua cjson doesn't encocode sparse arrays properly. 

If that where fixed in openresty, I would be in good shape. 

I'm going to close this bug. Thank you for the help.

**Comment by lordnynex** [comment]
The other issue is that this is being used in a tight loop for websocket recv_frame() https://github.com/openresty/lua-resty-websocket#recv_frame

It could be blocking long enough to wreck the loop.

**Comment by bungle** [comment]
Numbers are encoded just like libcjson does it. I'm not sure if it does it wrongly. It could. It's rather old and has not seen updates for two years. If the loop is really tight, it could be too slow, but short messages should take just a little bit of time, like 1 ms or something.

Yes, I added bunch of niceties here to encode values and sparse arrays in a way what you expect. Yes, that is a strangeness in Lua cJSON. There are a lot of decoders (in C and otherwise), but very few good ones that can actually encode. I would like to have LuaJIT optimized JSON implementation as well.

**Comment by bungle** [comment]
@lordnynex have you perhaps tried this:
https://github.com/openresty/lua-nginx-module/blob/master/t/lib/ljson.lua

**Comment by bungle** [comment]
If I decode and encode your example with lua-resty-libcjson this is what I get:

```json
[36, 9007199254740992, 8299743424320, {
}, [{
			"message":	"Hello, world!"
		}]]
```

**Comment by bungle** [comment]
Here are some conformance tests:
https://rawgit.com/miloyip/nativejson-benchmark/master/sample/conformance.html
